[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient
  bblanchon/ArduinoJson
  bogde/HX711
  adafruit/Adafruit PN532
build_flags =
  -D MQTT_MAX_PACKET_SIZE=1024
  -D WIFI_SSID='"FRITZ!Box 7530 BY"'
  -D WIFI_PASS='"14082001"'
  -D MQTT_HOST='"192.168.178.107"'
  -D MQTT_PORT=1883
[env:bed2]
build_flags =
  ${env.build_flags}
  -D ZONE_NAME='"bed2"'
  -D RELAY_LED_PIN=5
  -D RELAY_PUMP_PIN=23
  -D I2C_SDA=21
  -D I2C_SCL=22
  -D HX_DT=18
  -D HX_SCK=19
  -D SOIL_CISTERN_PIN=34
  -D SOIL_SOIL_PIN=35
  -D PN532_IRQ=4
  -D PN532_RESET=2
  -D PIN_STEP=25
  -D PIN_DIR=26
  -D PIN_EN=27
upload_port = /dev/ttyUSB0
[env:bed1]
build_flags =
  ${env.build_flags}
  -D ZONE_NAME='"bed1"'
  -D RELAY_LED_PIN=5
  -D RELAY_PUMP_PIN=23
  -D I2C_SDA=21
  -D I2C_SCL=22
  -D HX_DT=18
  -D HX_SCK=19
  -D SOIL_CISTERN_PIN=34
  -D SOIL_SOIL_PIN=35
  -D PN532_IRQ=4
  -D PN532_RESET=2
  -D PIN_STEP=25
  -D PIN_DIR=26
  -D PIN_EN=27
upload_port = /dev/ttyUSB1
